### ISSUE TITLE
[FLASH] Sauvegarde de l'état du ruban

### ISSUE THREAD

**Issue by Devdevdavid** [Devdevdavid/Domoticz#20]
Le principe de sauvegarde des paramètres du ruban en flash est déjà présent dans LightKit mais il n'intègre pas le mode démo. Il convient donc de l'ajouter.

De plus, maintenant que la gestions des paramètres stockés en flash a été modifiée pour la partie Wifi, il serait formidable d'utiliser le même système pour les paramètres du ruban (Une structure mappée en flash)

**Comment by Devdevdavid** [comment]
Fonction implémentée avec cd1c047da51280b5fabbcd16eadf33440f68778a

🧪 A tester !

**Comment by Pascal-Tours** [comment]
Fonction validée !
