### ISSUE TITLE
[Interface température] Utilisation de l'entrée OPT

### ISSUE THREAD

**Issue by Devdevdavid** [Devdevdavid/Domoticz#4]
Dans le cas de la board telegram buzzer, on aimerait que si l'entrée OPT est active alors le system d'Alarme doit être désactivée pour éviter que le buzzer sonne pour un dépassement de température contrôlé.

**Comment by Devdevdavid** [comment]
Le switch OPT agit désormais comme un forçage de l'alarme à OFF lorsque l'on est sur une `BOARD_TEMP_TELEGRAM_BUZZER`

Aussi, on signal le changement d'état du switch lorsque l'on est sur une  `BOARD_TEMP_TELEGRAM` par un message Telegram

Commit 8eb938f139db0d20c736f4ea2612ad9b956c25ee

**Comment by Pascal-Tours** [comment]
OK
