### ISSUE TITLE
[Interface température] Affichage de l'adresse des capteurs de température

### ISSUE THREAD

**Issue by Devdevdavid** [Devdevdavid/Domoticz#5]
Il serait intéressant de pouvoir visualiser l'adresse unique des capteurs de température connectées à la carte.
Ceci permettrait de marquer les sondes avec une petite étiquette pour une meilleure gestion.
On pourrait utiliser une nouvelle commande telegram pour cette fonctionnalité.

**Comment by Devdevdavid** [comment]
J'ai ajouté la commande /sensors qui permet de consulter la liste des capteurs de température détectés et d'afficher leur adresse unique.

Commit f5671ed207f2c48d73d7eb7f2ee2ff14f66081e0

**Comment by Pascal-Tours** [comment]
OK , 4 octets au lieu de 8 adresse capteur DS1820
