### ISSUE TITLE
[interface de température] Test de connexion toutes les 12h

### ISSUE THREAD

**Issue by Devdevdavid** [Devdevdavid/Domoticz#7]
Ré-implémenter la fonction de test de connexion par Telegram toutes les 12h.
On envoie un message Telegram pour dire que tout va bien.

**Comment by Devdevdavid** [comment]
J'ai ajouté la fonctionnalité. L'intervalle des notifications est fixé à 12h.
Pour désactiver la fonctionnalité, il suffit de définir le paramètre `SCRIPT_TELEGRAM_CONN_OK_NOTIFY_PERIOD` à 0.

Commit c63ab776e789e41d5bc96313e68d87ff90c38314

**Comment by Devdevdavid** [comment]
Du nouveau @Pascal-Tours sur ce point ?

**Comment by Pascal-Tours** [comment]
Sorry, cela fonctionne J

 

De : David DEVANT [mailto:notifications@github.com] 
Envoyé : lundi 24 août 2020 21:17
À : Devdevdavid/Pascal-Project
Cc : Pascal-Tours; Mention
Objet : Re: [Devdevdavid/Pascal-Project] [interface de température] Test de connexion toutes les 12h (#7)

 

Du nouveau @Pascal-Tours <https://github.com/Pascal-Tours>  sur ce point ?
